---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ cgit_packages }}"
    state: present

- name: Create cgit configuration
  ansible.builtin.template:
    src: cgitrc.j2
    dest: /etc/cgitrc
    owner: root
    group: www-data
    mode: 0640
    backup: true
  tags:
    - conf

- name: Create nginx configuration
  ansible.builtin.template:
    src: nginx.j2
    dest: "/etc/nginx/sites-available/\
           {{ cgit_hostname | default(ansible_hostname, true) }}.conf"
    owner: root
    group: root
    mode: 0640
    backup: true
  notify: Restart nginx
  tags:
    - conf

- name: Enable nginx configuration
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/\
          {{ cgit_hostname | default(ansible_hostname, true) }}.conf"
    dest: "/etc/nginx/sites-enabled/\
           {{ cgit_hostname | default(ansible_hostname, true) }}.conf"
    state: link
    owner: root
    group: root
    mode: 0640
  tags:
    - conf
