---
- name: Install required packages
  package:
    name: "{{ cgit_packages }}"
    state: present


- name: Create cgit configuration
  template:
    src: cgitrc.j2
    dest: /etc/cgitrc
    owner: root
    group: root
    mode: 0640
    backup: true
