---
- name: Prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Ubuntu
      block:
        - name: Create generic link for python
          ansible.builtin.file:
            state: link
            src: /usr/bin/python3
            dest: /usr/bin/python

    - name: Apt-get update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 36000

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - net-tools

    - name: Debug
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }} / {{ ansible_distribution_release }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
